/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Gayana
 */
public class GameUI extends javax.swing.JFrame {

    /**
     * Creates new form GameUI
     */
    public String palindromeWords[];
    public String normalWords[];
    String cardLables[];

    public GameUI() {
        initComponents();
        cardLables = new String[4];
        normalWords = new String[]{"Assume", "At", "Attack", "Attention",
            "Attorney", "Audience", "Author", "Authority", "Available",
            "Body", "Book", "Born", "Both", "Box", "Boy", "Break", "Bring", "Brother", "Budge",
            "Concern", "Condition", "Conference", "Congress", "Consider", "Contain", "Continue",
            "Control", "Cost", "Could", "Die",};

        palindromeWords = new String[]{"Anna",
            "Civic",
            "Kayak",
            "Level",
            "Madam",
            "Mom",
            "Noon",
            "Racecar",
            "Radar",
            "Redder",
            "Refer",
            "Repaper",
            "Rotator",
            "Rotor",
            "Sagas",
            "Solos",
            "Stats",
            "Tenet",
            "Wow",
            "Succus",
            "Tallat",
            "Terret",
            "Tirrit",
            "Deified",
            "Hadedah",
            "Halalah",
            "Reifier",
            "Reviver",
            "Rotator",
            "Rotavator",};

        shuffleArray();
        loadCards();
    }

    public void loadCards() {

        txtOne.setText(cardLables[0]);
        txtTwo.setText(cardLables[1]);
        txtThree.setText(cardLables[2]);
        txtFour.setText(cardLables[3]);

    }

    public void shuffleArray() {

        int index[] = new int[4];
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < 30; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        for (int i = 0; i < 4; i++) {
            index[i] = list.get(i);
        }

        cardLables[0] = normalWords[index[0]];
        cardLables[1] = normalWords[index[1]];
        cardLables[2] = normalWords[index[2]];
        cardLables[3] = palindromeWords[index[3]];

        list.clear();
        for (int i = 0; i < 4; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);

        int rgen = list.get(0);

        for (int i = 0; i < 4; i++) {
            int randomPosition = rgen;
            String temp = cardLables[i];
            cardLables[i] = cardLables[randomPosition];
            cardLables[randomPosition] = temp;
        }

    }

    public void clear() {
        lblMessage.setText("");
        txtOne.setBackground(Color.white);
        txtTwo.setBackground(Color.white);
        txtThree.setBackground(Color.white);
        txtFour.setBackground(Color.white);

    }

    public boolean palindromeChecker(String input) {
        //complete the code
        

        String temp2 = input.replaceAll("[^a-zA-Z0-9]", "").toLowerCase();
        Stack stack = new Stack();

        for (char c : temp2.toCharArray()) {
            stack.push(c);
        }
        
        for (char c : temp2.toCharArray()) {
            Link link = stack.pop();
            
            if (link == null || link.letter != c) {
                return false;
            }
        }

        return true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTwo = new javax.swing.JTextField();
        txtThree = new javax.swing.JTextField();
        txtFour = new javax.swing.JTextField();
        txtOne = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(165, 212, 251));

        txtTwo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtTwo.setForeground(new java.awt.Color(0, 0, 153));
        txtTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTwoMouseClicked(evt);
            }
        });

        txtThree.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtThree.setForeground(new java.awt.Color(0, 0, 153));
        txtThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThreeMouseClicked(evt);
            }
        });

        txtFour.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtFour.setForeground(new java.awt.Color(0, 0, 153));
        txtFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFourMouseClicked(evt);
            }
        });

        txtOne.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtOne.setForeground(new java.awt.Color(0, 0, 153));
        txtOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOneMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Let’s Try Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Palindrome Expert");

        jButton2.setBackground(new java.awt.Color(204, 0, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/childrens-birthday-card-bee-345-p.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOne, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOne, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOneMouseClicked
        // TODO add your handling code here:
        
        if(palindromeChecker(txtOne.getText())){
            txtOne.setBackground(Color.green);
            lblMessage.setText("Well done, your are a star!");
        }
        else{
            txtOne.setBackground(Color.red);
            lblMessage.setText("Oops try again!");
        }
  
    }//GEN-LAST:event_txtOneMouseClicked

    private void txtTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTwoMouseClicked

              // TODO add your handling code here:
        if(palindromeChecker(txtTwo.getText())){
            txtTwo.setBackground(Color.green);
            lblMessage.setText("Well done, your are a star!");
        }
        else{
            txtTwo.setBackground(Color.red);
            lblMessage.setText("Oops try again!");
        }
    }//GEN-LAST:event_txtTwoMouseClicked

    private void txtThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThreeMouseClicked
        // TODO add your handling code here:
        
        if(palindromeChecker(txtThree.getText())){
            txtThree.setBackground(Color.green);
            lblMessage.setText("Well done, your are a star!");
        }
        else{
            txtThree.setBackground(Color.red);
            lblMessage.setText("Oops try again!");
        }
    }//GEN-LAST:event_txtThreeMouseClicked

    private void txtFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFourMouseClicked
        // TODO add your handling code here:
        
        if(palindromeChecker(txtFour.getText())){
            txtFour.setBackground(Color.green);
            lblMessage.setText("Well done, your are a star!");
        }
        else{
            txtFour.setBackground(Color.red);
            lblMessage.setText("Oops try again!");
        }
    }//GEN-LAST:event_txtFourMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
        shuffleArray();
        loadCards();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtFour;
    private javax.swing.JTextField txtOne;
    private javax.swing.JTextField txtThree;
    private javax.swing.JTextField txtTwo;
    // End of variables declaration//GEN-END:variables
}
